# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9106f9ccacc7295ed944e019ca24071287ec14f7507c7661ee4502a1732e6f2d10cdcd453d74fc37039d224ae84494b1efacfadcdb3491578511e7b31ae99a8b

test:
  secret_key_base: 54d3d827e3b4b8e4c04f5e5c2c3d12ebca0a4005ac7abdc5b19b65aa030259e9d8fd2f7a340e68d6b7433dddbb34ffca9cef1369020358f0a4d43fb767b8233b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
